translation_api_export_with_prefix:
  path: api/translation/{languageKey}/{extensionKey}/{prefix}
  controller: Sinso\Translationapi\Controller\XliffController::export
  format: json
  requirements:
    languageKey: '[a-z]{2}'
  defaults:
    plugin: API

translation_api_export:
  path: api/translation/{languageKey}/{extensionKey}
  controller: Sinso\Translationapi\Controller\XliffController::export
  format: json
  requirements:
    languageKey: '[a-z]{2}'
    extensionKey: '.*'
  defaults:
    plugin: API
